name: Fetch Data
on:
  schedule:
    - cron: '0 0 * * *' # Daily
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Fetch CSV
        run: |
          curl -L "https://aware.com.au/bin/unitPriceExport?category=FUTURE_SAVER" -o data.csv
      - name: Copy to super data directory
        run: |
          mkdir -p data/super
          cp data.csv data/super/super.csv
      - name: Commit and Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.csv data/super/super.csv
          git commit -m "Update data" || echo "No changes"
          git push
      - name: Purge jsDelivr cache
        run: |
          curl -X PURGE "https://purge.jsdelivr.net/gh/x-byrne/Supaware@main/data/super/super.csv"
          curl -X PURGE "https://purge.jsdelivr.net/gh/x-byrne/Supaware@main/data.csv"
